// recipes.js — база рецептов для прикорма (30+)

const RECIPES = [
    // Пюре (6+ мес)
    {
        id: 'puree_courgette',
        name: 'Пюре из кабачка',
        age: 6,
        ingredients: ['кабачок'],
        prep: 'Очистить, нарезать кубиками, отварить до мягкости, измельчить блендером.',
        texture: 'пюре',
        approach: ['пюре'],
        allergens: [],
        iron: false,
        choking: false,
        storage: 'Хранить в холодильнике не более 2 суток, можно заморозить.'
    },
    {
        id: 'puree_broccoli',
        name: 'Пюре из брокколи',
        age: 6,
        ingredients: ['брокколи'],
        prep: 'Разобрать на соцветия, отварить до мягкости, измельчить блендером.',
        texture: 'пюре',
        approach: ['пюре'],
        allergens: [],
        iron: false,
        choking: false,
        storage: 'Хранить в холодильнике не более 2 суток, можно заморозить.'
    },
    {
        id: 'puree_pumpkin',
        name: 'Пюре из тыквы',
        age: 6,
        ingredients: ['тыква'],
        prep: 'Очистить, нарезать кубиками, запечь или отварить, измельчить.',
        texture: 'пюре',
        approach: ['пюре'],
        allergens: [],
        iron: false,
        choking: false,
        storage: 'Хранить в холодильнике не более 2 суток, можно заморозить.'
    },
    {
        id: 'puree_carrot_potato',
        name: 'Пюре из моркови и картофеля',
        age: 6,
        ingredients: ['морковь', 'картофель'],
        prep: 'Очистить, нарезать, отварить до мягкости, измельчить блендером.',
        texture: 'пюре',
        approach: ['пюре'],
        allergens: [],
        iron: false,
        choking: false,
        storage: 'Хранить в холодильнике не более 2 суток.'
    },
    {
        id: 'puree_apple_pear',
        name: 'Пюре из яблока и груши',
        age: 6,
        ingredients: ['яблоко', 'груша'],
        prep: 'Очистить, нарезать, отварить до мягкости, измельчить блендером.',
        texture: 'пюре',
        approach: ['пюре'],
        allergens: [],
        iron: false,
        choking: false,
        storage: 'Хранить в холодильнике не более 2 суток, можно заморозить.'
    },
    {
        id: 'puree_banana_avocado',
        name: 'Пюре из банана и авокадо',
        age: 6,
        ingredients: ['банан', 'авокадо'],
        prep: 'Размять вилкой до однородной массы.',
        texture: 'пюре',
        approach: ['пюре'],
        allergens: [],
        iron: false,
        choking: false,
        storage: 'Съесть сразу (авокадо темнеет).'
    },
    // Каши (6+ мес)
    {
        id: 'buckwheat_porridge',
        name: 'Гречневая каша',
        age: 6,
        ingredients: ['гречка', 'вода'],
        prep: 'Промыть крупу, залить водой, варить до готовности, измельчить блендером или протереть через сито.',
        texture: 'каша',
        approach: ['пюре', 'BLW'],
        allergens: [],
        iron: true,
        choking: false,
        storage: 'Хранить в холодильнике не более суток.'
    },
    {
        id: 'rice_porridge',
        name: 'Рисовая каша',
        age: 6,
        ingredients: ['рис', 'вода'],
        prep: 'Промыть, залить водой, варить до полной мягкости, измельчить.',
        texture: 'каша',
        approach: ['пюре'],
        allergens: [],
        iron: false,
        choking: false,
        storage: 'Хранить в холодильнике не более суток.'
    },
    {
        id: 'oatmeal_porridge',
        name: 'Овсяная каша',
        age: 6,
        ingredients: ['овсянка', 'вода/молоко'],
        prep: 'Сварить на воде или смеси, измельчить до нужной консистенции.',
        texture: 'каша',
        approach: ['пюре'],
        allergens: ['глютен'],
        iron: true,
        choking: false,
        storage: 'Хранить в холодильнике не более суток.'
    },
    {
        id: 'quinoa_porridge',
        name: 'Каша из киноа',
        age: 6,
        ingredients: ['киноа', 'вода'],
        prep: 'Промыть, варить 15 минут, измельчить блендером.',
        texture: 'каша',
        approach: ['пюре', 'BLW'],
        allergens: [],
        iron: true,
        choking: false,
        storage: 'Хранить в холодильнике не более суток.'
    },
    // Мясо (6+ мес)
    {
        id: 'turkey_puree',
        name: 'Пюре из индейки',
        age: 6,
        ingredients: ['индейка', 'вода'],
        prep: 'Отварить филе индейки, измельчить блендером, добавить немного бульона для консистенции.',
        texture: 'пюре',
        approach: ['пюре'],
        allergens: [],
        iron: true,
        choking: false,
        storage: 'Хранить в холодильнике не более суток.'
    },
    {
        id: 'beef_puree',
        name: 'Пюре из говядины',
        age: 6,
        ingredients: ['говядина', 'овощной бульон'],
        prep: 'Отварить говядину, измельчить блендером, добавить бульон.',
        texture: 'пюре',
        approach: ['пюре'],
        allergens: [],
        iron: true,
        choking: false,
        storage: 'Хранить в холодильнике не более суток.'
    },
    {
        id: 'chicken_puree',
        name: 'Пюре из курицы',
        age: 6,
        ingredients: ['курица', 'вода'],
        prep: 'Отварить куриное филе, измельчить блендером.',
        texture: 'пюре',
        approach: ['пюре'],
        allergens: [],
        iron: true,
        choking: false,
        storage: 'Хранить в холодильнике не более суток.'
    },
    // Рыба (8+ мес)
    {
        id: 'cod_puree',
        name: 'Пюре из трески',
        age: 8,
        ingredients: ['треска'],
        prep: 'Отварить рыбу без костей, измельчить блендером.',
        texture: 'пюре',
        approach: ['пюре'],
        allergens: ['рыба'],
        iron: false,
        choking: false,
        storage: 'Хранить в холодильнике не более суток.'
    },
    {
        id: 'salmon_puree',
        name: 'Пюре из лосося',
        age: 8,
        ingredients: ['лосось'],
        prep: 'Запечь или отварить лосося, удалить кости, измельчить.',
        texture: 'пюре',
        approach: ['пюре'],
        allergens: ['рыба'],
        iron: false,
        choking: false,
        storage: 'Хранить в холодильнике не более суток.'
    },
    // Яйцо (6+ мес)
    {
        id: 'egg_yolk_puree',
        name: 'Желток с овощами',
        age: 6,
        ingredients: ['яйцо', 'овощное пюре'],
        prep: 'Сварить яйцо вкрутую, отделить желток, размять и смешать с пюре.',
        texture: 'пюре',
        approach: ['пюре'],
        allergens: ['яйцо'],
        iron: true,
        choking: false,
        storage: 'Съесть сразу.'
    },
    // Бобовые (7+ мес)
    {
        id: 'lentil_puree',
        name: 'Пюре из красной чечевицы',
        age: 7,
        ingredients: ['красная чечевица', 'овощной бульон'],
        prep: 'Варить чечевицу до мягкости, измельчить блендером.',
        texture: 'пюре',
        approach: ['пюре'],
        allergens: [],
        iron: true,
        choking: false,
        storage: 'Хранить в холодильнике не более суток.'
    },
    // Комбинированные (7+ мес)
    {
        id: 'turkey_with_broccoli',
        name: 'Индейка с брокколи',
        age: 7,
        ingredients: ['индейка', 'брокколи'],
        prep: 'Отварить индейку и брокколи, измельчить блендером.',
        texture: 'пюре',
        approach: ['пюре'],
        allergens: [],
        iron: true,
        choking: false,
        storage: 'Хранить в холодильнике не более суток.'
    },
    {
        id: 'chicken_with_rice',
        name: 'Курица с рисом',
        age: 7,
        ingredients: ['курица', 'рис'],
        prep: 'Отварить курицу и рис, измельчить блендером.',
        texture: 'пюре',
        approach: ['пюре'],
        allergens: [],
        iron: true,
        choking: false,
        storage: 'Хранить в холодильнике не более суток.'
    },
    {
        id: 'beef_with_carrots',
        name: 'Говядина с морковью',
        age: 7,
        ingredients: ['говядина', 'морковь'],
        prep: 'Отварить говядину и морковь, измельчить.',
        texture: 'пюре',
        approach: ['пюре'],
        allergens: [],
        iron: true,
        choking: false,
        storage: 'Хранить в холодильнике не более суток.'
    },
    // BLW (6+ мес) — finger food
    {
        id: 'steamed_broccoli_floret',
        name: 'Соцветие брокколи (BLW)',
        age: 6,
        ingredients: ['брокколи'],
        prep: 'Отварить или приготовить на пару соцветие до мягкости (вилка легко протыкает).',
        texture: 'finger food',
        approach: ['BLW'],
        allergens: [],
        iron: false,
        choking: false,
        storage: 'Съесть сразу.'
    },
    {
        id: 'soft_carrot_stick',
        name: 'Морковь-брусок (BLW)',
        age: 8,
        ingredients: ['морковь'],
        prep: 'Отварить морковь до очень мягкого состояния, нарезать длинными брусочками.',
        texture: 'finger food',
        approach: ['BLW'],
        allergens: [],
        iron: false,
        choking: false,
        storage: 'Съесть сразу.'
    },
    {
        id: 'avocado_slice',
        name: 'Ломтик авокадо',
        age: 6,
        ingredients: ['авокадо'],
        prep: 'Нарезать авокадо крупными ломтиками, посыпать или предложить как есть.',
        texture: 'finger food',
        approach: ['BLW'],
        allergens: [],
        iron: false,
        choking: false,
        storage: 'Съесть сразу.'
    },
    {
        id: 'banana_stick',
        name: 'Банан-брусок',
        age: 6,
        ingredients: ['банан'],
        prep: 'Нарезать банан крупными брусочками (оставить часть кожуры для захвата).',
        texture: 'finger food',
        approach: ['BLW'],
        allergens: [],
        iron: false,
        choking: false,
        storage: 'Съесть сразу.'
    },
    // Каши с добавками (7+ мес)
    {
        id: 'oatmeal_with_apple',
        name: 'Овсяная каша с яблоком',
        age: 7,
        ingredients: ['овсянка', 'яблоко'],
        prep: 'Сварить овсянку, добавить тёртое яблоко.',
        texture: 'каша с кусочками',
        approach: ['пюре', 'смешанный'],
        allergens: ['глютен'],
        iron: true,
        choking: false,
        storage: 'Хранить в холодильнике не более суток.'
    },
    {
        id: 'buckwheat_with_pumpkin',
        name: 'Гречка с тыквой',
        age: 6,
        ingredients: ['гречка', 'тыква'],
        prep: 'Отварить гречку и тыкву, измельчить блендером.',
        texture: 'пюре',
        approach: ['пюре'],
        allergens: [],
        iron: true,
        choking: false,
        storage: 'Хранить в холодильнике не более суток.'
    },
    // Десерты (9+ мес)
    {
        id: 'pear_oat_biscuit',
        name: 'Грушевое печенье (без сахара)',
        age: 9,
        ingredients: ['груша', 'овсяные хлопья'],
        prep: 'Смешать тёртую грушу с овсяными хлопьями, сформировать печенье, запечь.',
        texture: 'finger food',
        approach: ['BLW', 'смешанный'],
        allergens: ['глютен'],
        iron: false,
        choking: false,
        storage: 'Хранить в герметичной банке 3–5 дней.'
    },
    // Семейные блюда (10+ мес)
    {
        id: 'family_meatballs',
        name: 'Мясные фрикадельки (без соли)',
        age: 10,
        ingredients: ['фарш говяжий', 'рис', 'лук', 'яйцо'],
        prep: 'Смешать ингредиенты, сформировать шарики, отварить или запечь.',
        texture: 'кусочки',
        approach: ['смешанный'],
        allergens: ['яйцо'],
        iron: true,
        choking: false,
        storage: 'Хранить в холодильнике до 2 суток, можно заморозить.'
    },
    {
        id: 'fish_cakes',
        name: 'Рыбные котлеты (без соли)',
        age: 10,
        ingredients: ['рыбное филе', 'картофель', 'яйцо'],
        prep: 'Измельчить рыбу и отварной картофель, добавить яйцо, сформировать котлеты, запечь.',
        texture: 'кусочки',
        approach: ['смешанный'],
        allergens: ['рыба', 'яйцо'],
        iron: false,
        choking: false,
        storage: 'Хранить в холодильнике до 2 суток, можно заморозить.'
    },
    {
        id: 'vegetable_stew',
        name: 'Рагу из овощей (семейное)',
        age: 10,
        ingredients: ['кабачок', 'морковь', 'картофель', 'лук', 'томат'],
        prep: 'Нарезать всё мелкими кубиками, тушить до мягкости (без соли).',
        texture: 'кусочки',
        approach: ['смешанный'],
        allergens: [],
        iron: false,
        choking: false,
        storage: 'Хранить в холодильнике до 2 суток.'
    },
    // Напитки
    {
        id: 'water_chart',
        name: 'Вода (предлагать в чашке)',
        age: 6,
        ingredients: ['вода'],
        prep: 'Предлагать воду из чашки во время еды.',
        texture: 'напиток',
        approach: ['все'],
        allergens: [],
        iron: false,
        choking: false,
        storage: 'Свежая вода.'
    }
];
